#import "../lib/theme-v2.typ": *

#show: textbook-v2

#set page(header: none, footer: none)

= 烟雾测试：c 域 符号

#include "../1a-number-sense/0-a00-overview-counting.typ"
#include "../1a-number-sense/0-a01-overview-fraction-ratio-foundation.typ"
#include "../1a-number-sense/0-a02-overview-number-line-algebra-bridge.typ"
#include "../1a-number-sense/1-a01-natural-number.typ"
#include "../1a-number-sense/1-a04-digit.typ"
#include "../1a-number-sense/1-a07-addition.typ"
#include "../1a-number-sense/1-a10-multiplication.typ"
#include "../1a-number-sense/1-a13-order-of-operations.typ"
#include "../1a-number-sense/1-a15-add-commutative.typ"
#include "../1a-number-sense/1-a17-mul-commutative.typ"
#include "../1a-number-sense/1-a20-factor-multiple.typ"
#include "../1a-number-sense/1-a23-prime.typ"
#include "../1a-number-sense/1-a25-prime-factorization.typ"
#include "../1a-number-sense/1-a28-fraction-definition.typ"
#include "../1a-number-sense/1-a31-mixed-number.typ"
#include "../1a-number-sense/1-a34-simplify.typ"
#include "../1a-number-sense/1-a38-fraction-add-sub.typ"
#include "../1a-number-sense/1-a41-decimal.typ"
#include "../1a-number-sense/1-a44-ratio.typ"
#include "../1a-number-sense/1-a47-decimal-fraction-conversion.typ"
#include "../1a-number-sense/1-a49-number-line.typ"
#include "../1a-number-sense/1-a52-opposite-number.typ"
#include "../1a-number-sense/1-a55-irrational-number.typ"
#include "../1a-number-sense/4-a00-review-counting.typ"
#include "../1a-number-sense/4-a01-review-fraction-ratio-foundation.typ"
#include "../1a-number-sense/4-a02-review-number-line-algebra-bridge.typ"
#include "../1b-shapes/0-b00-overview-geometry-foundation.typ"
#include "../1b-shapes/1-b01-point.typ"
#include "../1b-shapes/1-b04-ray.typ"
#include "../1b-shapes/1-b07-triangle.typ"
#include "../1b-shapes/1-b10-perimeter.typ"
#include "../1b-shapes/1-b13-area.typ"
#include "../1b-shapes/1-b17-volume.typ"
#include "../1b-shapes/1-b20-angle.typ"
#include "../1b-shapes/1-b23-acute-angle.typ"
#include "../1b-shapes/1-b26-complementary.typ"
#include "../1b-shapes/1-b29-parallel-lines.typ"
#include "../1b-shapes/1-b32-co-interior-supplementary.typ"
#include "../1b-shapes/1-b36-coordinate-system.typ"
#include "../1b-shapes/4-b00-review-geometry-foundation.typ"
#include "../2-foundation-transition/2-t00-overview.typ"
#include "../2-foundation-transition/2-t01-foundation-check.typ"
#include "../2-foundation-transition/2-t02-branch-entry-recaps.typ"
#include "../2-foundation-transition/2-t03-review.typ"
#include "../3a-symbols/0-c00-overview-algebra-deepening.typ"
#include "../3a-symbols/1-c01-variable.typ"
#include "../3a-symbols/1-c04-equation.typ"
#include "../3a-symbols/1-c07-polynomial.typ"
#include "../3a-symbols/1-c12-polynomial-multiply.typ"
#include "../3a-symbols/1-c15-power-notation.typ"
#include "../3a-symbols/1-c18-zero-exponent.typ"
#include "../3a-symbols/1-c21-factorization.typ"
#include "../3a-symbols/1-c25-rational-expression.typ"
#include "../3a-symbols/1-c28-common-denominator.typ"
#include "../3a-symbols/1-c31-rational-equation.typ"
#include "../3a-symbols/1-c34-linear-equation.typ"
#include "../3a-symbols/3-c37-system-of-equations.typ"
#include "../3a-symbols/3-c40-quadratic-equation.typ"
#include "../3a-symbols/3-c45-inequality.typ"
#include "../3a-symbols/2-c00-foundation-summary.typ"
#include "../3a-symbols/4-c00-review-algebra-deepening.typ"
