#import "../lib/theme-v2.typ": *

#show: textbook-v2

#set page(header: none, footer: none)

= 烟雾测试：主干收束闸门

#include "../a-number-sense/_overview-from-01-counting.typ"
#include "../a-number-sense/_overview-from-02-fraction-ratio-foundation.typ"
#include "../a-number-sense/_overview-from-04-number-line-algebra-bridge.typ"
#include "../a-number-sense/a01-natural-number.typ"
#include "../a-number-sense/a04-digit.typ"
#include "../a-number-sense/a07-addition.typ"
#include "../a-number-sense/a10-multiplication.typ"
#include "../a-number-sense/a13-order-of-operations.typ"
#include "../a-number-sense/a15-add-commutative.typ"
#include "../a-number-sense/a17-mul-commutative.typ"
#include "../a-number-sense/a20-factor-multiple.typ"
#include "../a-number-sense/a23-prime.typ"
#include "../a-number-sense/a25-prime-factorization.typ"
#include "../a-number-sense/a28-fraction-definition.typ"
#include "../a-number-sense/a31-mixed-number.typ"
#include "../a-number-sense/a34-simplify.typ"
#include "../a-number-sense/a38-fraction-add-sub.typ"
#include "../a-number-sense/a41-decimal.typ"
#include "../a-number-sense/a44-ratio.typ"
#include "../a-number-sense/a47-decimal-fraction-conversion.typ"
#include "../a-number-sense/a49-number-line.typ"
#include "../a-number-sense/a52-opposite-number.typ"
#include "../a-number-sense/a55-irrational-number.typ"
#include "../a-number-sense/_review-from-01-counting.typ"
#include "../a-number-sense/_review-from-02-fraction-ratio-foundation.typ"
#include "../a-number-sense/_review-from-04-number-line-algebra-bridge.typ"
#include "../b-shapes/_overview-from-03-geometry-foundation.typ"
#include "../b-shapes/b01-point.typ"
#include "../b-shapes/b04-ray.typ"
#include "../b-shapes/b07-triangle.typ"
#include "../b-shapes/b10-perimeter.typ"
#include "../b-shapes/b13-area.typ"
#include "../b-shapes/b17-volume.typ"
#include "../b-shapes/b20-angle.typ"
#include "../b-shapes/b23-acute-angle.typ"
#include "../b-shapes/b26-complementary.typ"
#include "../b-shapes/b29-parallel-lines.typ"
#include "../b-shapes/b32-co-interior-supplementary.typ"
#include "../b-shapes/b36-coordinate-system.typ"
#include "../b-shapes/_review-from-03-geometry-foundation.typ"
#include "../c-symbols/c01-variable.typ"
#include "../c-symbols/c04-equation.typ"
#include "../foundation-gate/00-overview.typ"
#include "../foundation-gate/01-foundation-check.typ"
#include "../foundation-gate/02-branch-entry-recaps.typ"
#include "../foundation-gate/03-review.typ"
